---
title: "Building Elegant Graphics with ggplot"
description: |
  In class exercise 01 Session 1 Date:01/15
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
options(htmitools.dir.verison = FALSE)
knitr::opts_chunk$set(
  fig.retina=3,
  echo = FALSE,
  echo = TRUE,
  message = FALSE,
  warning = FALSE
  )
```


#
```{r}
packages = c('tidyverse','ggrepel')
for(p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
    
  library(p, character.only = T)
}

```

```{r}
exam_data <-read.csv("data/Exam_data.csv")
```

# My first data visualization with ggplot2

```{r}
ggplot(data= exam_data,
       aes(x=MATHS)) +
       geom_histogram(
         bin=20,
         color="black",
         fill="light blue"
       )

```


```{r}
ggplot(data= exam_data,
       aes(x=MATHS,
           fill=GENDER)) +
       geom_histogram(
         bin=20,
         color="black",
         
       )

```
